"""CALM as training-data oracle for SubstrateHRLM.

CALM's 1002 deterministic functions give us infinite, correct labels
for math/compute problems. Instead of hand-coding target functions in
compositional_data templates, we let CALM compute the labels via
`safe_eval`. This closes the loop: the deterministic compute engine
trains the learned approximator.

Architecture:
  CompositionalTask (from compositional_data.py)
    ↑  labels generated by
  CALMOracle.sample(recipe)
    ↑  expression template like "is_prime({a} + {b})"
  safe_eval (CALM's 1002-function registry)

The bridge is pure: a recipe (NL-style expression) + variable ranges →
labeled examples. No training loop changes needed; the phase runner's
data pipeline consumes `CompositionalTask` as before.

Gate integration: `calm_verified_gate` replaces hand-coded gate_fn's.
Model prediction is checked against `safe_eval` of the same expression.
That's a much stronger correctness signal than argmax-matches-target
(which can be fooled by the data generation mismatching the gate).
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Callable, Iterable, Optional

from calm.expression import ExpressionError, safe_eval
from calm.llm_computer.compositional_data import (
    CompositionalTask, TaskTemplate,
)


@dataclass(frozen=True)
class CALMRecipe:
    """Declarative spec for generating CALM-labeled tasks.

    Attributes:
        name: human-readable template name.
        expression: a Python-expression template with {var} placeholders.
            Evaluated via CALM's safe_eval. Example: "is_prime({a}+{b})",
            "gcd({a}, {b})", "{a} * {b}".
        var_ranges: dict mapping var_name → (lo, hi) inclusive range.
        prompt_fn: callable(var_dict) → tuple[int, ...] that converts
            the variables into the sequence we feed the model as input.
        answer_fn: optional callable(calm_result) → int that converts
            CALM's answer (bool, int, float) into the target token ID.
            Default: round to int, cast bools to 0/1.
        cards_required: which cards the answer logically depends on
            (metadata only; not used for label generation).
        difficulty: metadata for curriculum tools.
    """
    name: str
    expression: str
    var_ranges: dict[str, tuple[int, int]]
    prompt_fn: Callable[[dict[str, int]], tuple[int, ...]]
    answer_fn: Callable[..., int] = None  # type: ignore
    cards_required: frozenset[str] = field(default_factory=frozenset)
    difficulty: int = 1


def _default_answer_fn(v):
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, (int, float)):
        return int(v)
    raise TypeError(f"CALM returned unrepresentable type: {type(v).__name__}")


class CALMOracle:
    """Generates labeled tasks by evaluating recipes via CALM's safe_eval."""

    def __init__(self):
        self._recipes: dict[str, CALMRecipe] = {}

    def register(self, recipe: CALMRecipe) -> None:
        if recipe.name in self._recipes:
            raise ValueError(f"recipe {recipe.name!r} already registered")
        self._recipes[recipe.name] = recipe

    def recipes(self) -> list[str]:
        return list(self._recipes.keys())

    def sample(
        self, recipe_name: str, n: int, seed: int = 0,
        max_retries: int = 5,
    ) -> list[CompositionalTask]:
        """Generate n labeled tasks for a recipe. Retries if CALM
        evaluation fails (e.g., factorial of large numbers overflowing)."""
        if recipe_name not in self._recipes:
            raise KeyError(f"unknown recipe {recipe_name!r}")
        recipe = self._recipes[recipe_name]
        answer_fn = recipe.answer_fn or _default_answer_fn
        rng = random.Random(seed)
        out: list[CompositionalTask] = []
        attempts = 0
        max_attempts = n * max_retries
        while len(out) < n and attempts < max_attempts:
            attempts += 1
            var_dict = {
                name: rng.randint(lo, hi)
                for name, (lo, hi) in recipe.var_ranges.items()
            }
            expr = recipe.expression.format(**var_dict)
            try:
                calm_result = safe_eval(expr)
                answer = answer_fn(calm_result)
                prompt = recipe.prompt_fn(var_dict)
                out.append(CompositionalTask(
                    prompt=prompt, answer=answer,
                    cards_required=recipe.cards_required,
                    difficulty=recipe.difficulty,
                    trace=f"calm_eval({expr})={calm_result}",
                ))
            except (ExpressionError, OverflowError, ValueError, TypeError):
                continue
        return out

    def build_template(self, recipe_name: str) -> TaskTemplate:
        """Wrap a recipe as a TaskTemplate for use with DatasetMix /
        PhaseRunner / CompositionalBenchmark."""
        if recipe_name not in self._recipes:
            raise KeyError(f"unknown recipe {recipe_name!r}")
        recipe = self._recipes[recipe_name]
        answer_fn = recipe.answer_fn or _default_answer_fn

        def sample_fn(rng: random.Random) -> CompositionalTask:
            for _ in range(10):  # bounded retry
                var_dict = {
                    name: rng.randint(lo, hi)
                    for name, (lo, hi) in recipe.var_ranges.items()
                }
                expr = recipe.expression.format(**var_dict)
                try:
                    calm_result = safe_eval(expr)
                    answer = answer_fn(calm_result)
                    prompt = recipe.prompt_fn(var_dict)
                    return CompositionalTask(
                        prompt=prompt, answer=answer,
                        cards_required=recipe.cards_required,
                        difficulty=recipe.difficulty,
                        trace=f"calm_eval({expr})={calm_result}",
                    )
                except (ExpressionError, OverflowError, ValueError, TypeError):
                    continue
            # Fallback: return zeros
            return CompositionalTask(
                prompt=(0,), answer=0,
                cards_required=recipe.cards_required,
                difficulty=recipe.difficulty,
                trace=f"calm_eval failed for {recipe.name}",
            )

        return TaskTemplate(
            name=recipe.name,
            cards_required=recipe.cards_required,
            difficulty=recipe.difficulty,
            sample_fn=sample_fn,
        )


# ----- Preset recipes (match our compiled/trained card library) -----

def recipe_adder_small() -> CALMRecipe:
    """a + b for a, b in [0, 3]. Matches compiled adder_tiny."""
    return CALMRecipe(
        name="calm_adder_small",
        expression="{a} + {b}",
        var_ranges={"a": (0, 3), "b": (0, 3)},
        prompt_fn=lambda v: (v["a"], v["b"]),
        cards_required=frozenset({"adder"}),
        difficulty=1,
    )


def recipe_is_prime_small() -> CALMRecipe:
    """is_prime(n) for n in [0, 6]. Matches adder's output range."""
    return CALMRecipe(
        name="calm_is_prime",
        expression="is_prime({n})",
        var_ranges={"n": (0, 6)},
        prompt_fn=lambda v: (v["n"],),
        cards_required=frozenset({"is_prime"}),
        difficulty=1,
    )


def recipe_is_sum_prime() -> CALMRecipe:
    """is_prime(a+b) — a genuine 2-card composition."""
    return CALMRecipe(
        name="calm_is_sum_prime",
        expression="is_prime({a} + {b})",
        var_ranges={"a": (0, 3), "b": (0, 3)},
        prompt_fn=lambda v: (v["a"], v["b"]),
        cards_required=frozenset({"adder", "is_prime"}),
        difficulty=2,
    )


def recipe_gcd_small() -> CALMRecipe:
    return CALMRecipe(
        name="calm_gcd",
        expression="gcd({a}, {b})",
        var_ranges={"a": (1, 7), "b": (1, 7)},
        prompt_fn=lambda v: (v["a"], v["b"]),
        cards_required=frozenset({"gcd"}),
        difficulty=1,
    )


def recipe_sum_mod2() -> CALMRecipe:
    """(a+b) mod 2 — parity of sum, two-card composition."""
    return CALMRecipe(
        name="calm_sum_parity",
        expression="({a} + {b}) % 2",
        var_ranges={"a": (0, 3), "b": (0, 3)},
        prompt_fn=lambda v: (v["a"], v["b"]),
        cards_required=frozenset({"adder", "modulo"}),
        difficulty=2,
    )


def recipe_max_ab() -> CALMRecipe:
    return CALMRecipe(
        name="calm_max_ab",
        expression="max({a}, {b})",
        var_ranges={"a": (0, 3), "b": (0, 3)},
        prompt_fn=lambda v: (v["a"], v["b"]),
        cards_required=frozenset({"compare"}),
        difficulty=1,
    )


def default_oracle() -> CALMOracle:
    """Pre-populated oracle with the recipes matching our card library."""
    oracle = CALMOracle()
    for r in [
        recipe_adder_small(),
        recipe_is_prime_small(),
        recipe_is_sum_prime(),
        recipe_gcd_small(),
        recipe_sum_mod2(),
        recipe_max_ab(),
    ]:
        oracle.register(r)
    return oracle


# ----- CALM-verified gates -----

def calm_verified_gate(
    predict_fn: Callable[[CompositionalTask], int],
    recipe: CALMRecipe,
    n_samples: int = 20,
    seed: int = 42,
) -> float:
    """Phase gate: model prediction must match CALM's answer.

    Returns accuracy in [0, 1]. Unlike hand-coded gate_fn's, this gate
    trusts ONLY CALM as the ground-truth oracle.
    """
    oracle = CALMOracle()
    oracle.register(recipe)
    tasks = oracle.sample(recipe.name, n=n_samples, seed=seed)
    if not tasks:
        return 0.0
    correct = sum(1 for t in tasks if predict_fn(t) == t.answer)
    return correct / len(tasks)
