"""Recursion MVP — substrate-generates-facades.

Phase B Level-1 minimum per `.claude/rules/recursion.md`:

  1. Given a (domain, failure-surface) pair where Gemma fails on
     prompts that CALM's safe_eval can answer exactly…
  2. Template-generate a new decode-path facade .py file, following
     the R46.2 / R22c / R53a skeleton.
  3. Validate the facade by running safe_eval on a held-out test set.
  4. Import + install + A/B live on Gemma.
  5. On pass: commit the facade as a permanent substrate capability.

This MVP skips step 2 of full-recursion (retrieve similar facades from
CodeExampleDB) and step 3 (have Gemma write new Python). Instead the
spec is a parameterized template — a deterministic code generator
gated by the CALM oracle. The "substrate built its own facade" property
holds: no human-written Python is needed for any new domain whose
shape matches (regex-parse + safe_eval evaluator + step-through bias).

Future: upgrade the template generator to a compiled planner card that
takes (failure_trace, oracle_signature) and emits a FacadeSpec. That
is the Level-2 MetaCard per `recursion.md`.

Usage:
    from calm.llm_computer.recursion import FacadeSpec, generate_facade

    spec = FacadeSpec(
        name="Factorial",
        module_name="factorial_auto",
        description="n! for small n",
        parse_patterns=[
            r"factorial\s+of\s+(-?\d+)",
            r"(-?\d+)\s*!",
            r"what\s+is\s+(-?\d+)\s+factorial",
        ],
        eval_expr="factorial({a})",   # safe_eval template
        max_operand=20,               # guard (factorial blows up)
    )  # noqa — docstring example, not executable

    path = generate_facade(spec, dest_dir="calm/llm_computer/facades")
    # path = '.../facades/factorial_auto.py'

    # Programmatic validation via safe_eval oracle
    from calm.llm_computer.recursion import validate_facade
    assert validate_facade(spec, [(5, 120), (7, 5040), (10, 3628800)])
"""
from __future__ import annotations

import importlib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class FacadeSpec:
    """Declarative spec for a new decode-path compute facade."""
    name: str                          # e.g. "Factorial" — PascalCase class prefix
    module_name: str                   # e.g. "factorial_auto" — .py file stem
    description: str                   # one-liner, populates docstring
    parse_patterns: list[str]          # regexes with ≥1 int group (the operand)
    eval_expr: str                     # safe_eval template, e.g. "factorial({a})"
    max_operand: Optional[int] = None  # reject operands beyond this (guard)
    operand_count: int = 1             # 1 or 2 — single vs paired operand
    boost: float = 50.0
    max_tokens: int = 40


_TEMPLATE = '''"""{description}

AUTO-GENERATED by calm/llm_computer/recursion.py. Template lifted from
NumberTheoryFacade / BaseConversionFacade (R46.2 decode-path skeleton).

Capability: parse {name} queries, evaluate via CALM safe_eval oracle,
deliver answer digits through Gemma's decode via step-through bias.

Commercial framing: substrate-generated facade, zero human-written
Python, CALM verification gate. Each domain-of-the-form (regex → single
integer answer) is now a parameter, not a code-write task.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

import torch

from calm.expression import ExpressionError, safe_eval


@dataclass
class {name}Result:
    prompt: str
    operands: Optional[tuple]
    value: Optional[int]
    generated: str
    parsed_answer: Optional[int]
    used_bias: bool


class {name}Facade:
    """{description}

    Parse → safe_eval → step-through digit bias. Identical mechanism to
    R46.2 / R22c / R53a. See `recursion.py` for the generator that
    produced this file.
    """

    DEFAULT_BOOST = {boost}
    DEFAULT_MAX_TOKENS = {max_tokens}
    MAX_OPERAND = {max_operand!r}
    OPERAND_COUNT = {operand_count}

    _PARSE_RES = [
{parse_res_literals}
    ]
    _EVAL_TEMPLATE = {eval_template!r}

    _SPACE_TOKEN_ID = 236743

    def __init__(self, boost: float = DEFAULT_BOOST,
                 max_tokens: int = DEFAULT_MAX_TOKENS,
                 device: str = "cuda"):
        self.boost = boost
        self.max_tokens = max_tokens
        self.device = device
        self._gemma = None
        self._tokenizer = None

    def install(self, gemma, tokenizer):
        self._gemma = gemma
        self._tokenizer = tokenizer

    def detach(self):
        self._gemma = None
        self._tokenizer = None

    def parse(self, prompt: str) -> Optional[tuple]:
        for pat in self._PARSE_RES:
            m = pat.search(prompt)
            if m:
                try:
                    groups = tuple(int(m.group(i + 1))
                                   for i in range(self.OPERAND_COUNT))
                except (ValueError, IndexError):
                    continue
                if self.MAX_OPERAND is not None:
                    if any(abs(g) > self.MAX_OPERAND for g in groups):
                        continue
                return groups
        return None

    def evaluate(self, operands: tuple) -> Optional[int]:
        if operands is None:
            return None
        try:
            if self.OPERAND_COUNT == 1:
                expr = self._EVAL_TEMPLATE.format(a=operands[0])
            else:
                expr = self._EVAL_TEMPLATE.format(a=operands[0], b=operands[1])
            val = safe_eval(expr)
            if isinstance(val, bool):
                return None
            if isinstance(val, int):
                return val
            if isinstance(val, float) and val.is_integer():
                return int(val)
        except (ExpressionError, Exception):
            return None
        return None

    def solve(self, prompt: str, *, max_tokens: Optional[int] = None,
              boost: Optional[float] = None, use_bias: bool = True):
        if self._gemma is None or self._tokenizer is None:
            raise RuntimeError("facade not installed — call install() first")
        mt = max_tokens if max_tokens is not None else self.max_tokens
        b = boost if boost is not None else self.boost

        operands = self.parse(prompt)
        value = self.evaluate(operands) if operands else None

        digit_ids: list[int] = []
        if use_bias and value is not None:
            digit_ids = self._gemma_digit_tokens(value)

        fire_bias = bool(digit_ids)
        text = self._generate(prompt, digit_ids if fire_bias else [], b, mt)
        parsed = self._parse_int(text)
        return {name}Result(
            prompt=prompt, operands=operands, value=value,
            generated=text, parsed_answer=parsed, used_bias=fire_bias,
        )

    def _gemma_digit_tokens(self, n: int) -> list[int]:
        ids = self._tokenizer.encode(str(n))
        if ids and ids[0] == 2:
            ids = ids[1:]
        if ids and ids[0] == self._SPACE_TOKEN_ID:
            ids = ids[1:]
        return ids

    @staticmethod
    def _parse_int(text: str) -> Optional[int]:
        normalized = text.replace(",", "")
        m = re.search(r"-?\\d{{1,15}}", normalized)
        return int(m.group(0)) if m else None

    def _generate(self, prompt: str, digit_token_ids: list[int],
                  boost: float, max_tokens: int) -> str:
        from calm.llm_computer.gemma_substrate import KVCache

        gemma = self._gemma
        tok = self._tokenizer
        if not prompt.rstrip().lower().endswith(("answer:", "= ")):
            prompt = prompt.rstrip() + " Answer: "
        ids = tok.encode(prompt)
        cache = KVCache(gemma.config.n_layers, device=self.device)
        gen = list(ids)
        digit_idx = 0 if digit_token_ids else -1

        POST_BIAS_BUDGET = 4

        with torch.no_grad():
            logits = gemma.forward(
                torch.tensor([gen]), device=self.device,
                kv_cache=cache, start_pos=0,
            )
            if 0 <= digit_idx < len(digit_token_ids):
                logits[0, -1, digit_token_ids[digit_idx]] += boost
                digit_idx += 1
            nxt = int(logits[0, -1].argmax())
            gen.append(nxt)

            post_bias_steps = 0
            for _ in range(max_tokens - 1):
                if hasattr(tok, "EOS_ID") and nxt == tok.EOS_ID:
                    break
                if digit_token_ids and digit_idx >= len(digit_token_ids):
                    post_bias_steps += 1
                    if post_bias_steps > POST_BIAS_BUDGET:
                        break
                logits = gemma.forward(
                    torch.tensor([[nxt]]), device=self.device,
                    kv_cache=cache, start_pos=len(gen) - 1,
                )
                if 0 <= digit_idx < len(digit_token_ids):
                    logits[0, -1, digit_token_ids[digit_idx]] += boost
                    digit_idx += 1
                nxt = int(logits[0, -1].argmax())
                gen.append(nxt)

        return tok.decode(gen[len(ids):]) if hasattr(tok, "decode") else ""
'''


def _render_parse_res_literals(patterns: list[str]) -> str:
    """Emit Python source for a list of regex patterns. `{pat!r}` already
    produces a valid non-raw string literal (with proper `\\` escaping);
    re.compile is fine with that — it treats the string as a regex. A
    leading `r` prefix would double-escape because `!r` already encoded
    backslashes for a standard string."""
    lines = []
    for pat in patterns:
        lines.append(f"        re.compile({pat!r}, re.IGNORECASE),")
    return "\n".join(lines)


_REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def generate_facade(
    spec: FacadeSpec,
    dest_dir: str | Path | None = None,
    overwrite: bool = False,
) -> Path:
    """Render the facade template and write to disk. Returns the
    absolute path. Default dest_dir is `<repo>/calm/llm_computer/facades`,
    resolved from the recursion.py file location."""
    if dest_dir is None:
        dest_dir = _REPO_ROOT / "calm" / "llm_computer" / "facades"
    dest = Path(dest_dir).resolve() / f"{spec.module_name}.py"
    if dest.exists() and not overwrite:
        raise FileExistsError(f"{dest} exists (pass overwrite=True to replace)")
    code = _TEMPLATE.format(
        name=spec.name,
        description=spec.description,
        boost=spec.boost,
        max_tokens=spec.max_tokens,
        max_operand=spec.max_operand,
        operand_count=spec.operand_count,
        parse_res_literals=_render_parse_res_literals(spec.parse_patterns),
        eval_template=spec.eval_expr,
    )
    # Syntax gate: compile to AST before writing so a broken spec never
    # lands on disk as an importable-but-broken facade.
    compile(code, str(dest), "exec")
    dest.write_text(code)
    return dest


def validate_facade(
    spec: FacadeSpec,
    test_cases: list,
) -> tuple[int, int]:
    """Run the CALM oracle on `test_cases` and check the spec evaluates
    correctly — BEFORE we write the facade file or install on Gemma.
    Oracle gate per recursion.md §'Why this is safe where RLAIF fails'.

    `test_cases`: list of `(operand, expected)` or `((o1, o2), expected)`
    depending on spec.operand_count.

    Returns (pass_count, total). If pass_count < total, the spec is
    broken — do NOT generate the facade.
    """
    from calm.expression import safe_eval, ExpressionError

    passed = 0
    for operand, expected in test_cases:
        if spec.operand_count == 1:
            a = operand if not isinstance(operand, (tuple, list)) else operand[0]
            expr = spec.eval_expr.format(a=a)
        else:
            a, b = operand
            expr = spec.eval_expr.format(a=a, b=b)
        try:
            got = safe_eval(expr)
            if isinstance(got, bool):
                continue
            if isinstance(got, float) and got.is_integer():
                got = int(got)
            if got == expected:
                passed += 1
        except (ExpressionError, Exception):
            continue
    return passed, len(test_cases)


def import_facade_class(spec: FacadeSpec):
    """Import the generated module and return its class. Forces module
    reload so re-generation under the same name picks up the latest
    code (important during iterative testing)."""
    mod_path = f"calm.llm_computer.facades.{spec.module_name}"
    if mod_path in importlib.sys.modules:
        importlib.reload(importlib.sys.modules[mod_path])
    else:
        importlib.import_module(mod_path)
    mod = importlib.sys.modules[mod_path]
    cls = getattr(mod, f"{spec.name}Facade")
    return cls


# --- Canonical demo spec: Factorial ---

FACTORIAL_SPEC = FacadeSpec(
    name="Factorial",
    module_name="factorial_auto",
    description="Factorial (n!) via CALM safe_eval oracle.",
    parse_patterns=[
        r"factorial\s+of\s+(-?\d+)",
        r"(-?\d+)\s*!",
        r"what\s+is\s+(-?\d+)\s+factorial",
    ],
    eval_expr="factorial({a})",
    max_operand=20,
    operand_count=1,
    max_tokens=30,
)


# --- Canonical demo spec: Fibonacci ---

FIBONACCI_SPEC = FacadeSpec(
    name="Fibonacci",
    module_name="fibonacci_auto",
    description="Fibonacci(n) via CALM safe_eval oracle.",
    parse_patterns=[
        r"fibonacci\s+of\s+(-?\d+)",
        r"fibonacci\s*\(\s*(-?\d+)\s*\)",
        r"(-?\d+)(?:st|nd|rd|th)\s+fibonacci",
        r"what\s+is\s+fib(?:onacci)?\s+(-?\d+)",
    ],
    eval_expr="fibonacci({a})",
    max_operand=100,
    operand_count=1,
    max_tokens=30,
)


# --- M1 arc: more auto-generated facades (2026-04-22) ---

COMBINATIONS_SPEC = FacadeSpec(
    name="Combinations",
    module_name="combinations_auto",
    description="combinations(n, k) — binomial coefficient C(n, k).",
    parse_patterns=[
        r"(-?\d+)\s+choose\s+(-?\d+)",
        r"\bC\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
        r"combinations?\s+of\s+(-?\d+)\s+(?:choose|taken?)\s+(-?\d+)",
        r"combinations?\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
        r"\bbinomial\s+coefficient\s+of\s+(-?\d+)\s+and\s+(-?\d+)",
    ],
    eval_expr="combinations({a}, {b})",
    max_operand=100,
    operand_count=2,
    max_tokens=40,
)

PERMUTATIONS_SPEC = FacadeSpec(
    name="Permutations",
    module_name="permutations_auto",
    description="permutations(n, k) — P(n, k) = n! / (n-k)!.",
    parse_patterns=[
        r"(-?\d+)\s+permute\s+(-?\d+)",
        r"\bP\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
        r"permutations?\s+of\s+(-?\d+)\s+(?:taken?|choose)\s+(-?\d+)",
        r"permutations?\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
    ],
    eval_expr="permutations({a}, {b})",
    max_operand=50,
    operand_count=2,
    max_tokens=40,
)

POWER_SPEC = FacadeSpec(
    name="Power",
    module_name="power_auto",
    description="pow(a, b) — a raised to the power b, integer exponent.",
    parse_patterns=[
        # "2 to the power 10" / "2 to the 10th power"
        r"(-?\d+)\s+to\s+the\s+(?:power\s+(?:of\s+)?)?(-?\d+)(?:(?:st|nd|rd|th)\s+power)?",
        # "2^10" / "2 ^ 10"
        r"(-?\d+)\s*\^\s*(-?\d+)",
        # "2**10"
        r"(-?\d+)\s*\*\*\s*(-?\d+)",
        # "pow(2, 10)"
        r"\bpow\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
        # "2 raised to the 10"
        r"(-?\d+)\s+raised\s+to\s+(?:the\s+)?(-?\d+)(?:(?:st|nd|rd|th)\s+power)?",
    ],
    eval_expr="pow({a}, {b})",
    max_operand=30,    # pow(2, 30) is ~1B; keep bounded for sane tokens
    operand_count=2,
    max_tokens=40,
)

NEXT_PRIME_SPEC = FacadeSpec(
    name="NextPrime",
    module_name="next_prime_auto",
    description="next_prime(n) — smallest prime strictly greater than n.",
    parse_patterns=[
        r"next\s+prime\s+(?:after|greater\s+than|above)\s+(-?\d+)",
        r"smallest\s+prime\s+(?:greater|larger|bigger)\s+than\s+(-?\d+)",
        r"prime\s+(?:number\s+)?after\s+(-?\d+)",
        r"next_prime\s*\(\s*(-?\d+)\s*\)",
    ],
    eval_expr="next_prime({a})",
    max_operand=100000,
    operand_count=1,
    max_tokens=30,
)


# ============================================================================
# Level-2: MetaFacade — auto-synthesize the FacadeSpec itself
# ============================================================================
#
# Given just (fn_name, arity, domain_name), emit a FacadeSpec whose
# regex catalog covers the canonical NL patterns for that operation.
#
# Upgrade over Level-1: the spec itself is no longer hand-written.
# Code-generation responsibility moves from human to substrate while
# CALM oracle validation remains the correctness gate.
#
# Bounded synthesis scope: regex templates are deterministic per arity
# (1-arg / 2-arg math function with integer operands). Level-3
# (MetaMetaFacade) extends this to operations with non-integer outputs,
# non-regex parsing (e.g. date strings), and structural arity>=3.


class MetaFacade:
    """Synthesizes FacadeSpec objects from a function-name + arity pair.

    The template library codifies the common English patterns for
    N-argument math functions. Each pattern is a regex with N integer
    capture groups. The synthesizer assembles a FacadeSpec using these
    patterns plus a standard safe_eval template.

    Usage:
        spec = MetaFacade.from_oracle(
            fn_name="combinations",
            arity=2,
            max_operand=100,
            extra_patterns=[r"(-?\\d+)\\s+choose\\s+(-?\\d+)"],
        )
        # spec is functionally equivalent to a hand-written FacadeSpec
    """

    @staticmethod
    def _canonical_patterns_1arg(fn_name: str) -> list[str]:
        """Regexes for single-operand NL patterns around `fn_name`."""
        fn = re.escape(fn_name)
        return [
            # "fn_name(N)" / "fn_name ( N )"
            rf"{fn}\s*\(\s*(-?\d+)\s*\)",
            # "fn_name of N"
            rf"{fn}\s+of\s+(-?\d+)",
            # "what is fn_name N"
            rf"(?:what\s+is\s+)?{fn}\s+(-?\d+)",
        ]

    @staticmethod
    def _canonical_patterns_2arg(fn_name: str) -> list[str]:
        """Regexes for two-operand NL patterns around `fn_name`."""
        fn = re.escape(fn_name)
        return [
            # "fn_name(A, B)"
            rf"{fn}\s*\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)",
            # "fn_name of A and B"
            rf"{fn}\s+of\s+(-?\d+)\s+and\s+(-?\d+)",
            # "A fn_name B" — for verb-like names ("choose", "permute")
            rf"(-?\d+)\s+{fn}\s+(-?\d+)",
            # "fn_name A by B" / "fn_name A with B"
            rf"{fn}\s+(-?\d+)\s+(?:by|with|taken)\s+(-?\d+)",
        ]

    @classmethod
    def from_oracle(
        cls,
        fn_name: str,
        arity: int,
        domain_name: str | None = None,
        module_name: str | None = None,
        description: str | None = None,
        max_operand: int | None = None,
        max_tokens: int = 40,
        extra_patterns: list[str] | None = None,
    ) -> FacadeSpec:
        """Synthesize a FacadeSpec for a safe_eval oracle function.

        `fn_name`: name in safe_eval (e.g. "factorial", "combinations").
        `arity`: 1 or 2.
        `domain_name`: PascalCase class-prefix (defaults to Capitalized fn_name).
        `module_name`: snake_case file stem (defaults to "{fn_name}_auto").
        `max_operand`: guard beyond which the facade rejects.
        `extra_patterns`: user-supplied regex templates appended AFTER the
            canonical patterns (lower priority — canonical first-match-wins).
        """
        if arity not in (1, 2):
            raise ValueError(f"arity must be 1 or 2, got {arity}")

        domain = domain_name or fn_name.capitalize()
        module = module_name or f"{fn_name.lower()}_auto"
        desc = description or f"{fn_name}(...) via CALM safe_eval oracle."

        if arity == 1:
            patterns = cls._canonical_patterns_1arg(fn_name)
            eval_expr = f"{fn_name}({{a}})"
        else:
            patterns = cls._canonical_patterns_2arg(fn_name)
            eval_expr = f"{fn_name}({{a}}, {{b}})"

        if extra_patterns:
            patterns.extend(extra_patterns)

        return FacadeSpec(
            name=domain,
            module_name=module,
            description=desc,
            parse_patterns=patterns,
            eval_expr=eval_expr,
            max_operand=max_operand,
            operand_count=arity,
            max_tokens=max_tokens,
        )

    @classmethod
    def batch_from_oracles(
        cls,
        oracle_specs: list[dict],
    ) -> list[FacadeSpec]:
        """Emit a FacadeSpec list from a list of oracle descriptors.
        Each dict passes **kwargs to from_oracle.

        Example:
            specs = MetaFacade.batch_from_oracles([
                {"fn_name": "factorial", "arity": 1, "max_operand": 20},
                {"fn_name": "combinations", "arity": 2, "max_operand": 100},
            ])
        """
        return [cls.from_oracle(**d) for d in oracle_specs]
