"""
CALM v0.1 GBNF grammar generator.

Produces a GBNF grammar compatible with llama.cpp's grammar engine
that constrains LLM output inside <calm>...</calm> blocks to valid
CALM instruction syntax. Used during inference to prevent the model
from emitting syntactically invalid CALM programs.

Option B extension: each instruction line can optionally be followed
by ` -> [...]` showing the LLM's claimed stack state. The harness
validates this claim against stack_vm.py and injects <error> on
mismatch.

Usage:
    from calm.grammar import generate_gbnf
    grammar = generate_gbnf()                    # builtins only
    grammar = generate_gbnf(["wasm_add", "fft"]) # + backend words
"""

from __future__ import annotations

from typing import List, Optional


# The 20 CALM v0.1 builtins (from stack_vm.py:default_dispatcher).
BUILTINS_ZERO_ARG = [
    "add", "sub", "mul", "div", "mod",
    "neg", "abs", "dup", "drop", "swap", "over", "rot",
    "eq", "lt", "gt", "emit", "halt",
]

# These builtins consume the next token as an argument.
BUILTINS_WITH_ARG = {
    "push": "literal",   # push <literal>
    ":": "ident",        # : <name>
}


def generate_gbnf(
    backend_words: Optional[List[str]] = None,
    option_b: bool = True,
) -> str:
    """
    Generate a GBNF grammar string for CALM v0.1.

    Args:
        backend_words: extra word names registered by backends
                       (e.g. ["wasm_add", "fft"]). Must match
                       [a-z_][a-z0-9_]* — validated at generation time.
        option_b:      if True, each instruction line may end with
                       ` -> [...]` (the LLM's stack-state claim).
    Returns:
        A GBNF grammar string ready for llama.cpp.
    """
    backend_words = backend_words or []
    for w in backend_words:
        if not w or not w[0].isalpha() and w[0] != "_":
            raise ValueError(f"invalid backend word: {w!r}")

    # Build the zero-arg alternatives: builtins + ";" + backend words.
    zero_arg_words = BUILTINS_ZERO_ARG + [";"] + backend_words
    zero_alt = " | ".join(f'"{w}"' for w in zero_arg_words)

    # Option B: stack state claim suffix, or <pending> for backend dispatch.
    if option_b:
        stack_claim = '\nstack-claim  ::= " -> [" stack-items "]" | " -> <pending>"'
        stack_items = '\nstack-items  ::= "" | stack-val ( ", " stack-val )*'
        stack_val = '\nstack-val    ::= int-lit | float-lit | bool-lit | str-lit'
        line_suffix = " stack-claim?"
    else:
        stack_claim = ""
        stack_items = ""
        stack_val = ""
        line_suffix = ""

    grammar = f"""\
# CALM v0.1 GBNF grammar
# Auto-generated by calm/grammar.py

root         ::= "<calm>" nl (line nl)* "</calm>"
line         ::= ws (comment | instruction{line_suffix})
instruction  ::= push-insn | def-insn | zero-insn | call-insn | word-insn
push-insn    ::= "push " literal
def-insn     ::= ": " ident
zero-insn    ::= {zero_alt}
call-insn    ::= "call " ident
word-insn    ::= ident
comment      ::= "\\\\" [^\\n]*{stack_claim}{stack_items}{stack_val}
literal      ::= int-lit | float-lit | str-lit | bool-lit
int-lit      ::= "-"? [0-9]+
float-lit    ::= "-"? [0-9]+ "." [0-9]+
str-lit      ::= "\\"" [^\\"]* "\\""
bool-lit     ::= "true" | "false"
ident        ::= [a-z_] [a-z0-9_]*
ws           ::= [ \\t]*
nl           ::= "\\n"
"""
    return grammar


def write_gbnf(path: str, **kwargs) -> str:
    """Generate and write the grammar to a file. Returns the grammar string."""
    grammar = generate_gbnf(**kwargs)
    with open(path, "w") as f:
        f.write(grammar)
    return grammar


if __name__ == "__main__":
    print(generate_gbnf())
