"""Phase-0 native-full-stack scaffold for HRM-Text-1.58.

This package is intentionally contract-only. It records the native ternary
stack seams, source anchors, ledger rows, FP exceptions, attribution hooks, and
acceptance metrics without implementing kernels, trainer entrypoints, or live
run integration.
"""
from __future__ import annotations

from calm.hrm_text_158.native_full_stack.attribution import (
    ATTRIBUTION_HOOK_POINTS,
    ATTRIBUTION_INTEGRITY_CHECKS,
    LIVE_C1353FD5_OBSERVATIONS,
    AttributionHookPoint,
    AttributionIntegrityCheck,
)
from calm.hrm_text_158.native_full_stack.activation_relief import (
    ACTIVATION_RELIEF_SCHEMA_VERSION,
    DEFERRED_GPU_MEASUREMENT_NOTE,
    MODE_LOSSLESS_RECOMPUTE,
    MODE_LOSSY_ACTIVATION_STORAGE,
    MODE_OFF,
    REQUIRED_ACTIVATION_RELIEF_MEASUREMENT_FIELDS,
    TARGET_GRAD_ENABLED_RECURRENCE,
    TERMINAL_DEPENDENT_TUNING_FIELDS,
    TIER1_LOSSLESS_RECOMPUTE,
    TIER2_LOSSY_ACTIVATION_STORAGE_DEFERRED,
    ActivationReliefDecision,
    ActivationReliefPolicy,
    normalize_activation_relief_policy,
    recurrence_checkpoint_decisions,
    should_checkpoint_recurrence,
    validate_activation_relief_measurement,
)
from calm.hrm_text_158.native_full_stack.contracts import (
    IMPLEMENTATION_STATUS_SKELETON_ONLY,
    PROJECTION_GROUPS,
    SUBSYSTEM_CONTRACTS,
    SubsystemContract,
)
from calm.hrm_text_158.native_full_stack.fp_exceptions import (
    FP_EXCEPTION_REGISTRY,
    FPException,
)
from calm.hrm_text_158.native_full_stack.global_rate_cap import (
    CAP_ORDERING_HASH_SEED,
    CPU_GLUE_NOT_KERNEL_NOTE,
    DEFERRED_NON_SCOPE,
    SCRATCH_S1_GLOBAL_CAP_ANNEAL_STEP,
    SCRATCH_S1_GLOBAL_CAP_MAX,
    SCRATCH_S1_GLOBAL_CAP_START,
    GlobalRateCapOrderingMode,
    GlobalRateCapResult,
    GlobalRateCapRow,
    GlobalRateCapSpec,
    GlobalRateCapTensorInput,
    GlobalRateCapTensorResult,
    apply_global_rate_cap_reference,
    global_rate_cap_priority_rows,
    order_global_rate_cap_rows,
    scratch_s1_global_cap_contract,
    scratch_s1_global_cap_for_step,
    select_global_rate_cap_rows,
    tensor_offsets_for_vote_update_states,
    validate_global_rate_cap_inputs,
)
from calm.hrm_text_158.native_full_stack.ledger import (
    LEDGER_SCHEMA_VERSION,
    PHASE0_LEDGER_ROWS,
    LedgerRow,
)
from calm.hrm_text_158.native_full_stack.metrics import (
    ACCEPTANCE_METRICS,
    AcceptanceMetric,
    first_class_metric_names,
)
from calm.hrm_text_158.native_full_stack.qscale_linear import (
    INT8_LEVELS_TRANSITIONAL_NOTE,
    QScaleLinearConfig,
    QScaleWeightFormat,
    QScaleWeightState,
    qscale_linear_reference,
    qscale_linear_triton,
    validate_qscale_weight_state,
)
from calm.hrm_text_158.native_full_stack.source_pointers import (
    ACTIVE_HRM_REPO_ROOT,
    HISTORICAL_NON_ANCHOR_POINTERS,
    LIVE_S1_TRAINER_POINTER,
    PHASE0_SOURCE_POINTERS,
    SourcePointer,
)
from calm.hrm_text_158.native_full_stack.vote_update import (
    DEFERRED_GLOBAL_CAP,
    INT16_ACC_TRANSITIONAL_NOTE,
    INT8_Q_TRANSITIONAL_NOTE,
    RUN_GPU_VOTE_UPDATE_ENV,
    VoteUpdateAccumulatorFormat,
    VoteUpdateInputs,
    VoteUpdatePlan,
    VoteUpdateQFormat,
    VoteUpdateResult,
    VoteUpdateSpec,
    VoteUpdateState,
    VoteUpdateVoteFormat,
    apply_integer_vote_update_reference,
    plan_integer_vote_update_reference,
    validate_vote_update_contract,
    vote_update_preplan_triton,
)

__all__ = [
    "ACTIVE_HRM_REPO_ROOT",
    "ACCEPTANCE_METRICS",
    "ACTIVATION_RELIEF_SCHEMA_VERSION",
    "ATTRIBUTION_HOOK_POINTS",
    "ATTRIBUTION_INTEGRITY_CHECKS",
    "ActivationReliefDecision",
    "ActivationReliefPolicy",
    "AttributionHookPoint",
    "AttributionIntegrityCheck",
    "CAP_ORDERING_HASH_SEED",
    "CPU_GLUE_NOT_KERNEL_NOTE",
    "DEFERRED_NON_SCOPE",
    "DEFERRED_GPU_MEASUREMENT_NOTE",
    "AcceptanceMetric",
    "FP_EXCEPTION_REGISTRY",
    "FPException",
    "GlobalRateCapOrderingMode",
    "GlobalRateCapResult",
    "GlobalRateCapRow",
    "GlobalRateCapSpec",
    "GlobalRateCapTensorInput",
    "GlobalRateCapTensorResult",
    "HISTORICAL_NON_ANCHOR_POINTERS",
    "IMPLEMENTATION_STATUS_SKELETON_ONLY",
    "INT16_ACC_TRANSITIONAL_NOTE",
    "INT8_LEVELS_TRANSITIONAL_NOTE",
    "INT8_Q_TRANSITIONAL_NOTE",
    "LEDGER_SCHEMA_VERSION",
    "LIVE_C1353FD5_OBSERVATIONS",
    "LIVE_S1_TRAINER_POINTER",
    "LedgerRow",
    "MODE_LOSSLESS_RECOMPUTE",
    "MODE_LOSSY_ACTIVATION_STORAGE",
    "MODE_OFF",
    "PHASE0_LEDGER_ROWS",
    "PHASE0_SOURCE_POINTERS",
    "PROJECTION_GROUPS",
    "QScaleLinearConfig",
    "QScaleWeightFormat",
    "QScaleWeightState",
    "REQUIRED_ACTIVATION_RELIEF_MEASUREMENT_FIELDS",
    "RUN_GPU_VOTE_UPDATE_ENV",
    "SCRATCH_S1_GLOBAL_CAP_ANNEAL_STEP",
    "SCRATCH_S1_GLOBAL_CAP_MAX",
    "SCRATCH_S1_GLOBAL_CAP_START",
    "SUBSYSTEM_CONTRACTS",
    "SourcePointer",
    "SubsystemContract",
    "TARGET_GRAD_ENABLED_RECURRENCE",
    "TERMINAL_DEPENDENT_TUNING_FIELDS",
    "TIER1_LOSSLESS_RECOMPUTE",
    "TIER2_LOSSY_ACTIVATION_STORAGE_DEFERRED",
    "VoteUpdateAccumulatorFormat",
    "VoteUpdateInputs",
    "VoteUpdatePlan",
    "VoteUpdateQFormat",
    "VoteUpdateResult",
    "VoteUpdateSpec",
    "VoteUpdateState",
    "VoteUpdateVoteFormat",
    "DEFERRED_GLOBAL_CAP",
    "apply_global_rate_cap_reference",
    "apply_integer_vote_update_reference",
    "first_class_metric_names",
    "global_rate_cap_priority_rows",
    "normalize_activation_relief_policy",
    "order_global_rate_cap_rows",
    "plan_integer_vote_update_reference",
    "qscale_linear_reference",
    "qscale_linear_triton",
    "recurrence_checkpoint_decisions",
    "scratch_s1_global_cap_contract",
    "scratch_s1_global_cap_for_step",
    "select_global_rate_cap_rows",
    "should_checkpoint_recurrence",
    "tensor_offsets_for_vote_update_states",
    "validate_activation_relief_measurement",
    "validate_global_rate_cap_inputs",
    "validate_qscale_weight_state",
    "validate_vote_update_contract",
    "vote_update_preplan_triton",
]
