(module
  ;; CALM math module — integer and float arithmetic for wasm backend.
  ;; Compiled to .wasm and loaded by calm/backends/wasm_ops.py.

  ;; Integer arithmetic (i64)
  (func (export "i_add") (param i64 i64) (result i64)
    local.get 0 local.get 1 i64.add)
  (func (export "i_sub") (param i64 i64) (result i64)
    local.get 0 local.get 1 i64.sub)
  (func (export "i_mul") (param i64 i64) (result i64)
    local.get 0 local.get 1 i64.mul)
  (func (export "i_div") (param i64 i64) (result i64)
    local.get 0 local.get 1 i64.div_s)
  (func (export "i_mod") (param i64 i64) (result i64)
    local.get 0 local.get 1 i64.rem_s)
  (func (export "i_neg") (param i64) (result i64)
    i64.const 0 local.get 0 i64.sub)
  (func (export "i_abs") (param i64) (result i64)
    (if (result i64) (i64.lt_s (local.get 0) (i64.const 0))
      (then (i64.sub (i64.const 0) (local.get 0)))
      (else (local.get 0))))
  (func (export "i_pow") (param $base i64) (param $exp i64) (result i64)
    (local $result i64)
    (local.set $result (i64.const 1))
    (block $done
      (loop $loop
        (br_if $done (i64.le_s (local.get $exp) (i64.const 0)))
        (local.set $result (i64.mul (local.get $result) (local.get $base)))
        (local.set $exp (i64.sub (local.get $exp) (i64.const 1)))
        (br $loop)))
    (local.get $result))

  ;; Float arithmetic (f64)
  (func (export "f_add") (param f64 f64) (result f64)
    local.get 0 local.get 1 f64.add)
  (func (export "f_sub") (param f64 f64) (result f64)
    local.get 0 local.get 1 f64.sub)
  (func (export "f_mul") (param f64 f64) (result f64)
    local.get 0 local.get 1 f64.mul)
  (func (export "f_div") (param f64 f64) (result f64)
    local.get 0 local.get 1 f64.div)
  (func (export "f_sqrt") (param f64) (result f64)
    local.get 0 f64.sqrt)
  (func (export "f_floor") (param f64) (result f64)
    local.get 0 f64.floor)
  (func (export "f_ceil") (param f64) (result f64)
    local.get 0 f64.ceil)
  (func (export "f_abs") (param f64) (result f64)
    local.get 0 f64.abs)

  ;; GCD via Euclidean algorithm
  (func (export "i_gcd") (param $a i64) (param $b i64) (result i64)
    (local $t i64)
    ;; abs(a), abs(b)
    (if (i64.lt_s (local.get $a) (i64.const 0))
      (then (local.set $a (i64.sub (i64.const 0) (local.get $a)))))
    (if (i64.lt_s (local.get $b) (i64.const 0))
      (then (local.set $b (i64.sub (i64.const 0) (local.get $b)))))
    (block $done
      (loop $loop
        (br_if $done (i64.eqz (local.get $b)))
        (local.set $t (i64.rem_s (local.get $a) (local.get $b)))
        (local.set $a (local.get $b))
        (local.set $b (local.get $t))
        (br $loop)))
    (local.get $a))
)
