"""fibonacci(...) via CALM safe_eval oracle.

AUTO-GENERATED by calm/llm_computer/recursion.py. Template lifted from
NumberTheoryFacade / BaseConversionFacade (R46.2 decode-path skeleton).

Capability: parse FibonacciMeta queries, evaluate via CALM safe_eval oracle,
deliver answer digits through Gemma's decode via step-through bias.

Commercial framing: substrate-generated facade, zero human-written
Python, CALM verification gate. Each domain-of-the-form (regex → single
integer answer) is now a parameter, not a code-write task.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

import torch

from calm.expression import ExpressionError, safe_eval


@dataclass
class FibonacciMetaResult:
    prompt: str
    operands: Optional[tuple]
    value: Optional[int]
    generated: str
    parsed_answer: Optional[int]
    used_bias: bool


class FibonacciMetaFacade:
    """fibonacci(...) via CALM safe_eval oracle.

    Parse → safe_eval → step-through digit bias. Identical mechanism to
    R46.2 / R22c / R53a. See `recursion.py` for the generator that
    produced this file.
    """

    DEFAULT_BOOST = 50.0
    DEFAULT_MAX_TOKENS = 40
    MAX_OPERAND = 50
    OPERAND_COUNT = 1

    _PARSE_RES = [
        re.compile('fibonacci\\s*\\(\\s*(-?\\d+)\\s*\\)', re.IGNORECASE),
        re.compile('fibonacci\\s+of\\s+(-?\\d+)', re.IGNORECASE),
        re.compile('(?:what\\s+is\\s+)?fibonacci\\s+(-?\\d+)', re.IGNORECASE),
    ]
    _EVAL_TEMPLATE = 'fibonacci({a})'

    _SPACE_TOKEN_ID = 236743

    def __init__(self, boost: float = DEFAULT_BOOST,
                 max_tokens: int = DEFAULT_MAX_TOKENS,
                 device: str = "cuda"):
        self.boost = boost
        self.max_tokens = max_tokens
        self.device = device
        self._gemma = None
        self._tokenizer = None

    def install(self, gemma, tokenizer):
        self._gemma = gemma
        self._tokenizer = tokenizer

    def detach(self):
        self._gemma = None
        self._tokenizer = None

    def parse(self, prompt: str) -> Optional[tuple]:
        for pat in self._PARSE_RES:
            m = pat.search(prompt)
            if m:
                try:
                    groups = tuple(int(m.group(i + 1))
                                   for i in range(self.OPERAND_COUNT))
                except (ValueError, IndexError):
                    continue
                if self.MAX_OPERAND is not None:
                    if any(abs(g) > self.MAX_OPERAND for g in groups):
                        continue
                return groups
        return None

    def evaluate(self, operands: tuple) -> Optional[int]:
        if operands is None:
            return None
        try:
            if self.OPERAND_COUNT == 1:
                expr = self._EVAL_TEMPLATE.format(a=operands[0])
            else:
                expr = self._EVAL_TEMPLATE.format(a=operands[0], b=operands[1])
            val = safe_eval(expr)
            if isinstance(val, bool):
                return None
            if isinstance(val, int):
                return val
            if isinstance(val, float) and val.is_integer():
                return int(val)
        except (ExpressionError, Exception):
            return None
        return None

    def solve(self, prompt: str, *, max_tokens: Optional[int] = None,
              boost: Optional[float] = None, use_bias: bool = True):
        if self._gemma is None or self._tokenizer is None:
            raise RuntimeError("facade not installed — call install() first")
        mt = max_tokens if max_tokens is not None else self.max_tokens
        b = boost if boost is not None else self.boost

        operands = self.parse(prompt)
        value = self.evaluate(operands) if operands else None

        digit_ids: list[int] = []
        if use_bias and value is not None:
            digit_ids = self._gemma_digit_tokens(value)

        fire_bias = bool(digit_ids)
        text = self._generate(prompt, digit_ids if fire_bias else [], b, mt)
        parsed = self._parse_int(text)
        return FibonacciMetaResult(
            prompt=prompt, operands=operands, value=value,
            generated=text, parsed_answer=parsed, used_bias=fire_bias,
        )

    def _gemma_digit_tokens(self, n: int) -> list[int]:
        ids = self._tokenizer.encode(str(n))
        if ids and ids[0] == 2:
            ids = ids[1:]
        if ids and ids[0] == self._SPACE_TOKEN_ID:
            ids = ids[1:]
        return ids

    @staticmethod
    def _parse_int(text: str) -> Optional[int]:
        normalized = text.replace(",", "")
        m = re.search(r"-?\d{1,15}", normalized)
        return int(m.group(0)) if m else None

    def _generate(self, prompt: str, digit_token_ids: list[int],
                  boost: float, max_tokens: int) -> str:
        from calm.llm_computer.gemma_substrate import KVCache

        gemma = self._gemma
        tok = self._tokenizer
        if not prompt.rstrip().lower().endswith(("answer:", "= ")):
            prompt = prompt.rstrip() + " Answer: "
        ids = tok.encode(prompt)
        cache = KVCache(gemma.config.n_layers, device=self.device)
        gen = list(ids)
        digit_idx = 0 if digit_token_ids else -1

        POST_BIAS_BUDGET = 4

        with torch.no_grad():
            logits = gemma.forward(
                torch.tensor([gen]), device=self.device,
                kv_cache=cache, start_pos=0,
            )
            if 0 <= digit_idx < len(digit_token_ids):
                logits[0, -1, digit_token_ids[digit_idx]] += boost
                digit_idx += 1
            nxt = int(logits[0, -1].argmax())
            gen.append(nxt)

            post_bias_steps = 0
            for _ in range(max_tokens - 1):
                if hasattr(tok, "EOS_ID") and nxt == tok.EOS_ID:
                    break
                if digit_token_ids and digit_idx >= len(digit_token_ids):
                    post_bias_steps += 1
                    if post_bias_steps > POST_BIAS_BUDGET:
                        break
                logits = gemma.forward(
                    torch.tensor([[nxt]]), device=self.device,
                    kv_cache=cache, start_pos=len(gen) - 1,
                )
                if 0 <= digit_idx < len(digit_token_ids):
                    logits[0, -1, digit_token_ids[digit_idx]] += boost
                    digit_idx += 1
                nxt = int(logits[0, -1].argmax())
                gen.append(nxt)

        return tok.decode(gen[len(ids):]) if hasattr(tok, "decode") else ""
