"""permutations(n, k) — P(n, k) = n! / (n-k)!.

AUTO-GENERATED by calm/llm_computer/recursion.py. Template lifted from
NumberTheoryFacade / BaseConversionFacade (R46.2 decode-path skeleton).

Capability: parse Permutations queries, evaluate via CALM safe_eval oracle,
deliver answer digits through Gemma's decode via step-through bias.

Commercial framing: substrate-generated facade, zero human-written
Python, CALM verification gate. Each domain-of-the-form (regex → single
integer answer) is now a parameter, not a code-write task.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

import torch

from calm.expression import ExpressionError, safe_eval


@dataclass
class PermutationsResult:
    prompt: str
    operands: Optional[tuple]
    value: Optional[int]
    generated: str
    parsed_answer: Optional[int]
    used_bias: bool


class PermutationsFacade:
    """permutations(n, k) — P(n, k) = n! / (n-k)!.

    Parse → safe_eval → step-through digit bias. Identical mechanism to
    R46.2 / R22c / R53a. See `recursion.py` for the generator that
    produced this file.
    """

    DEFAULT_BOOST = 50.0
    DEFAULT_MAX_TOKENS = 40
    MAX_OPERAND = 50
    OPERAND_COUNT = 2
    OPERAND_TYPE = 'int'   # "int" or "str"
    OUTPUT_TYPE = 'int'     # "int" or "bool"
    BOOL_TRUE_STR = 'Yes'
    BOOL_FALSE_STR = 'No'

    _PARSE_RES = [
        re.compile('(-?\\d+)\\s+permute\\s+(-?\\d+)', re.IGNORECASE),
        re.compile('\\bP\\s*\\(\\s*(-?\\d+)\\s*,\\s*(-?\\d+)\\s*\\)', re.IGNORECASE),
        re.compile('permutations?\\s+of\\s+(-?\\d+)\\s+(?:taken?|choose)\\s+(-?\\d+)', re.IGNORECASE),
        re.compile('permutations?\\s*\\(\\s*(-?\\d+)\\s*,\\s*(-?\\d+)\\s*\\)', re.IGNORECASE),
    ]
    _EVAL_TEMPLATE = 'permutations({a}, {b})'

    _SPACE_TOKEN_ID = 236743

    def __init__(self, boost: float = DEFAULT_BOOST,
                 max_tokens: int = DEFAULT_MAX_TOKENS,
                 device: str = "cuda"):
        self.boost = boost
        self.max_tokens = max_tokens
        self.device = device
        self._gemma = None
        self._tokenizer = None

    def install(self, gemma, tokenizer):
        self._gemma = gemma
        self._tokenizer = tokenizer

    def detach(self):
        self._gemma = None
        self._tokenizer = None

    def parse(self, prompt: str) -> Optional[tuple]:
        for pat in self._PARSE_RES:
            m = pat.search(prompt)
            if m:
                try:
                    if self.OPERAND_TYPE == "int":
                        groups = tuple(int(m.group(i + 1))
                                       for i in range(self.OPERAND_COUNT))
                        if self.MAX_OPERAND is not None:
                            if any(abs(g) > self.MAX_OPERAND for g in groups):
                                continue
                    else:
                        # operand_type == "str" — keep raw capture
                        groups = tuple(m.group(i + 1)
                                       for i in range(self.OPERAND_COUNT))
                except (ValueError, IndexError):
                    continue
                return groups
        return None

    def evaluate(self, operands: tuple):
        """Returns int|bool|None depending on OUTPUT_TYPE. For "int"
        returns int; for "bool" returns bool. None on eval failure."""
        if operands is None:
            return None
        try:
            if self.OPERAND_COUNT == 1:
                expr = self._EVAL_TEMPLATE.format(a=operands[0])
            else:
                expr = self._EVAL_TEMPLATE.format(a=operands[0], b=operands[1])
            val = safe_eval(expr)
            if self.OUTPUT_TYPE == "bool":
                if isinstance(val, bool):
                    return val
                return None
            # default: int output
            if isinstance(val, bool):
                return None
            if isinstance(val, int):
                return val
            if isinstance(val, float) and val.is_integer():
                return int(val)
        except (ExpressionError, Exception):
            return None
        return None

    def solve(self, prompt: str, *, max_tokens: Optional[int] = None,
              boost: Optional[float] = None, use_bias: bool = True):
        if self._gemma is None or self._tokenizer is None:
            raise RuntimeError("facade not installed — call install() first")
        mt = max_tokens if max_tokens is not None else self.max_tokens
        b = boost if boost is not None else self.boost

        operands = self.parse(prompt)
        value = self.evaluate(operands) if operands else None

        bias_ids: list[int] = []
        if use_bias and value is not None:
            if self.OUTPUT_TYPE == "bool":
                bias_ids = self._bool_bias_tokens(value)
            else:
                bias_ids = self._gemma_digit_tokens(value)

        fire_bias = bool(bias_ids)
        text = self._generate(prompt, bias_ids if fire_bias else [], b, mt)
        # Parsed answer interpretation depends on OUTPUT_TYPE
        if self.OUTPUT_TYPE == "bool":
            parsed = self._parse_bool(text)
        else:
            parsed = self._parse_int(text)
        return PermutationsResult(
            prompt=prompt, operands=operands, value=value,
            generated=text, parsed_answer=parsed, used_bias=fire_bias,
        )

    def _gemma_digit_tokens(self, n: int) -> list[int]:
        ids = self._tokenizer.encode(str(n))
        if ids and ids[0] == 2:
            ids = ids[1:]
        if ids and ids[0] == self._SPACE_TOKEN_ID:
            ids = ids[1:]
        return ids

    def _bool_bias_tokens(self, val: bool) -> list[int]:
        """Bias sequence for bool answers. Emits tokens for BOOL_TRUE_STR
        or BOOL_FALSE_STR. Keep leading ▁ if present — capitalized words
        usually merge the space into the first BPE token (e.g. ▁Yes)."""
        answer = self.BOOL_TRUE_STR if val else self.BOOL_FALSE_STR
        ids = self._tokenizer.encode(answer)
        if ids and ids[0] == 2:
            ids = ids[1:]
        return ids

    @staticmethod
    def _parse_int(text: str) -> Optional[int]:
        normalized = text.replace(",", "")
        m = re.search(r"-?\d{1,15}", normalized)
        return int(m.group(0)) if m else None

    def _parse_bool(self, text: str) -> Optional[bool]:
        low = text.lower()
        t = self.BOOL_TRUE_STR.lower()
        f = self.BOOL_FALSE_STR.lower()
        # First occurrence wins
        ti = low.find(t)
        fi = low.find(f)
        if ti == -1 and fi == -1:
            # Fallback: yes/no/true/false
            for pat, v in [(r"\byes\b", True), (r"\btrue\b", True),
                           (r"\bno\b", False), (r"\bfalse\b", False)]:
                if re.search(pat, low):
                    return v
            return None
        if ti == -1:
            return False
        if fi == -1:
            return True
        return ti < fi

    def _generate(self, prompt: str, digit_token_ids: list[int],
                  boost: float, max_tokens: int) -> str:
        from calm.llm_computer.gemma_substrate import KVCache

        gemma = self._gemma
        tok = self._tokenizer
        if not prompt.rstrip().lower().endswith(("answer:", "= ")):
            prompt = prompt.rstrip() + " Answer: "
        ids = tok.encode(prompt)
        cache = KVCache(gemma.config.n_layers, device=self.device)
        gen = list(ids)
        digit_idx = 0 if digit_token_ids else -1

        POST_BIAS_BUDGET = 4

        with torch.no_grad():
            logits = gemma.forward(
                torch.tensor([gen]), device=self.device,
                kv_cache=cache, start_pos=0,
            )
            if 0 <= digit_idx < len(digit_token_ids):
                logits[0, -1, digit_token_ids[digit_idx]] += boost
                digit_idx += 1
            nxt = int(logits[0, -1].argmax())
            gen.append(nxt)

            post_bias_steps = 0
            for _ in range(max_tokens - 1):
                if hasattr(tok, "EOS_ID") and nxt == tok.EOS_ID:
                    break
                if digit_token_ids and digit_idx >= len(digit_token_ids):
                    post_bias_steps += 1
                    if post_bias_steps > POST_BIAS_BUDGET:
                        break
                logits = gemma.forward(
                    torch.tensor([[nxt]]), device=self.device,
                    kv_cache=cache, start_pos=len(gen) - 1,
                )
                if 0 <= digit_idx < len(digit_token_ids):
                    logits[0, -1, digit_token_ids[digit_idx]] += boost
                    digit_idx += 1
                nxt = int(logits[0, -1].argmax())
                gen.append(nxt)

        return tok.decode(gen[len(ids):]) if hasattr(tok, "decode") else ""
